#!/usr/bin/env bash
# scripts/checkpoint-enhance.sh
# Post-processes checkpoint.md files to add git context and diff summaries.
#
# Usage:
#   bash scripts/checkpoint-enhance.sh [checkpoint_path]
#
# If no path given, finds the most recent checkpoint in ~/.local/share/mimocode/memory/sessions/
#
# What it adds:
#   - §12 Git context: recent commits, branch info
#   - §13 Code changes: diff summaries per modified file

set -euo pipefail

# Colors (NC = no-color reset, used by all log_* functions)
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}▶ $1${NC}"; }
log_success() { echo -e "${GREEN}✓ $1${NC}"; }
log_error() { echo -e "${RED}✗ $1${NC}"; }

# Find checkpoint path
CHECKPOINT="${1:-}"
if [[ -z "$CHECKPOINT" ]]; then
    MEMORY_BASE="${HOME}/.local/share/mimocode/memory/sessions"
    CHECKPOINT=$(find "$MEMORY_BASE" -name "checkpoint.md" -type f 2>/dev/null | sort -t/ -k10 -r | head -1)
    if [[ -z "$CHECKPOINT" ]]; then
        log_error "No checkpoint files found in $MEMORY_BASE"
        exit 1
    fi
    log_info "Using most recent checkpoint: $CHECKPOINT"
fi

if [[ ! -f "$CHECKPOINT" ]]; then
    log_error "Checkpoint not found: $CHECKPOINT"
    exit 1
fi

# Determine git repo (look for .git in checkpoint's session path or current dir)
SESSION_DIR=$(dirname "$CHECKPOINT")
REPO_DIR=""
for candidate in "$(pwd)" "$(dirname "$SESSION_DIR")" "$HOME"; do
    if [[ -d "$candidate/.git" ]]; then
        REPO_DIR="$candidate"
        break
    fi
done

if [[ -z "$REPO_DIR" ]]; then
    log_info "No git repo found, skipping git context"
    exit 0
fi

log_info "Git repo: $REPO_DIR"

# Generate git context section
GIT_SECTION=""
if [[ -d "$REPO_DIR/.git" ]]; then
    BRANCH=$(git -C "$REPO_DIR" branch --show-current 2>/dev/null || echo "unknown")
    LAST_COMMIT=$(git -C "$REPO_DIR" log --oneline -1 2>/dev/null || echo "no commits")
    RECENT_COMMITS=$(git -C "$REPO_DIR" log --oneline -5 2>/dev/null || echo "")
    
    GIT_SECTION="## §12 Git context
_Git repository state at checkpoint time. Auto-generated by checkpoint-enhance.sh._

- **Branch**: \`$BRANCH\`
- **Latest commit**: \`$LAST_COMMIT\`

### Recent commits (last 5)
\`\`\`
$RECENT_COMMITS
\`\`\`
"
fi

# Generate diff summary section
DIFF_SECTION=""
# Extract file paths from §6 of checkpoint
# shellcheck disable=SC2016  # Single quotes are intentional — this is a grep regex, not a shell expansion.
FILES_IN_CHECKPOINT=$(grep -oP '`[^`]+\.(py|ts|tsx|js|jsx|yaml|yml|sh|md)`' "$CHECKPOINT" | tr -d '`' | sort -u | head -20)

if [[ -n "$FILES_IN_CHECKPOINT" ]]; then
    DIFF_ENTRIES=""
    while IFS= read -r file; do
        if [[ -f "$REPO_DIR/$file" ]]; then
            # Get file stats
            LINES=$(wc -l < "$REPO_DIR/$file" 2>/dev/null || echo "?")
            LAST_MOD=$(git -C "$REPO_DIR" log -1 --format="%h %s" -- "$file" 2>/dev/null || echo "no git history")
            
            # Get diff stats if file is modified
            DIFF_STAT=$(git -C "$REPO_DIR" diff --stat HEAD -- "$file" 2>/dev/null | tail -1 || echo "")
            
            ENTRY="- \`$file\` ($LINES LOC) — last modified: $LAST_MOD"
            if [[ -n "$DIFF_STAT" ]]; then
                ENTRY="$ENTRY
  - Uncommitted changes: $DIFF_STAT"
            fi
            DIFF_ENTRIES="$DIFF_ENTRIES$ENTRY
"
        fi
    done <<< "$FILES_IN_CHECKPOINT"
    
    if [[ -n "$DIFF_ENTRIES" ]]; then
        DIFF_SECTION="## §13 Code changes summary
_Diff summaries for files referenced in this checkpoint. Auto-generated by checkpoint-enhance.sh._

$DIFF_ENTRIES"
    fi
fi

# Check if sections already exist (avoid duplicates)
if grep -q "## §12 Git context" "$CHECKPOINT"; then
    log_info "§12 Git context already exists, skipping"
    GIT_SECTION=""
fi
if grep -q "## §13 Code changes summary" "$CHECKPOINT"; then
    log_info "§13 Code changes summary already exists, skipping"
    DIFF_SECTION=""
fi

# Append sections
if [[ -n "$GIT_SECTION" || -n "$DIFF_SECTION" ]]; then
    # Add separator if file doesn't end with newline
    if [[ -n "$(tail -c 1 "$CHECKPOINT")" ]]; then
        echo "" >> "$CHECKPOINT"
    fi
    
    if [[ -n "$GIT_SECTION" ]]; then
        echo "" >> "$CHECKPOINT"
        echo "$GIT_SECTION" >> "$CHECKPOINT"
        log_success "Added §12 Git context"
    fi
    
    if [[ -n "$DIFF_SECTION" ]]; then
        echo "" >> "$CHECKPOINT"
        echo "$DIFF_SECTION" >> "$CHECKPOINT"
        log_success "Added §13 Code changes summary"
    fi
    
    log_success "Checkpoint enhanced: $CHECKPOINT"
else
    log_info "Nothing to add — checkpoint already up to date"
fi
